
name: Build and Deploy to Strato

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Strato via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: '5017916096.ssh.w2.strato.hosting'
        username: 'su262094'
        password: 'Test123456.'
        port: 22
        local_path: './dist/*'
        remote_path: '/'
        sftpArgs: '-o ConnectTimeout=5'
