
name: Build and Deploy to Strato

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy via SFTP to Strato
      uses: sebastianpopp/ssh-sftp-deploy@v4.2.1
      with:
        server: 5017916096.w2.strato-hosting
        username: su262094
        password: Test123456.
        protocol: SFTP
        port: 22
        local-dir: ./dist/
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
          README.md
          package*.json
